package pojo;

// Generated Jun 7, 2015 1:31:52 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "Permission")
public class Permission implements java.io.Serializable {

	private int permissionId;
	private String policy;
	private Set<User> users = new HashSet<User>(0);

	public Permission() {
	}

	public Permission(int permissionId) {
		this.permissionId = permissionId;
	}

	public Permission(int permissionId, String policy, Set<User> users) {
		this.permissionId = permissionId;
		this.policy = policy;
		this.users = users;
	}

	@Id
	@Column(name = "PermissionID", unique = true, nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "Policy")
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
