package pojo;

// Generated Jun 7, 2015 1:31:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistrationInfomation generated by hbm2java
 */
@Entity
@Table(name = "RegistrationInfomation")
public class RegistrationInfomation implements java.io.Serializable {

	private int regisId;
	private Classe classe;
	private Thematic thematic;
	private int userId;
	private Date regisTime;

	public RegistrationInfomation() {
	}

	public RegistrationInfomation(int regisId, Classe classe,
			Thematic thematic, int userId, Date regisTime) {
		this.regisId = regisId;
		this.classe = classe;
		this.thematic = thematic;
		this.userId = userId;
		this.regisTime = regisTime;
	}

	@Id
	@Column(name = "RegisID", unique = true, nullable = false)
	public int getRegisId() {
		return this.regisId;
	}

	public void setRegisId(int regisId) {
		this.regisId = regisId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ClassID", nullable = false)
	public Classe getClasse() {
		return this.classe;
	}

	public void setClasse(Classe classe) {
		this.classe = classe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ThematicID", nullable = false)
	public Thematic getThematic() {
		return this.thematic;
	}

	public void setThematic(Thematic thematic) {
		this.thematic = thematic;
	}

	@Column(name = "UserID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegisTime", nullable = false, length = 23)
	public Date getRegisTime() {
		return this.regisTime;
	}

	public void setRegisTime(Date regisTime) {
		this.regisTime = regisTime;
	}

}
