package pojo;

// Generated Jun 7, 2015 1:31:52 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TimeTable generated by hbm2java
 */
@Entity
@Table(name = "TimeTable")
public class TimeTable implements java.io.Serializable {

	private int timeTableId;
	private Serializable details;
	private Set<Classe> classes = new HashSet<Classe>(0);

	public TimeTable() {
	}

	public TimeTable(int timeTableId, Serializable details) {
		this.timeTableId = timeTableId;
		this.details = details;
	}

	public TimeTable(int timeTableId, Serializable details, Set<Classe> classes) {
		this.timeTableId = timeTableId;
		this.details = details;
		this.classes = classes;
	}

	@Id
	@Column(name = "TimeTableID", unique = true, nullable = false)
	public int getTimeTableId() {
		return this.timeTableId;
	}

	public void setTimeTableId(int timeTableId) {
		this.timeTableId = timeTableId;
	}

	@Column(name = "Details", nullable = false)
	public Serializable getDetails() {
		return this.details;
	}

	public void setDetails(Serializable details) {
		this.details = details;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeTable")
	public Set<Classe> getClasses() {
		return this.classes;
	}

	public void setClasses(Set<Classe> classes) {
		this.classes = classes;
	}

}
