package pojo;

// Generated Jun 7, 2015 1:31:52 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User_", uniqueConstraints = @UniqueConstraint(columnNames = "Email"))
public class User implements java.io.Serializable {

	private int userId;
	private Permission permission;
	private String email;
	private String pwd;
	private String fullName;
	private Date dob;
	private String addr;
	private String phoneNumber;
	private Integer status;
	private Set<UserFeedback> userFeedbacks = new HashSet<UserFeedback>(0);

	public User() {
	}

	public User(int userId, Permission permission, String email,
			String pwd, String fullName, Date dob,
			String addr, String phoneNumber) {
		this.userId = userId;
		this.permission = permission;
		this.email = email;
		this.pwd = pwd;
		this.fullName = fullName;
		this.dob = dob;
		this.addr = addr;
		this.phoneNumber = phoneNumber;
	}

	public User(int userId, Permission permission, String email,
			String pwd, String fullName, Date dob,
			String addr, String phoneNumber, Integer status,
			Set<UserFeedback> userFeedbacks) {
		this.userId = userId;
		this.permission = permission;
		this.email = email;
		this.pwd = pwd;
		this.fullName = fullName;
		this.dob = dob;
		this.addr = addr;
		this.phoneNumber = phoneNumber;
		this.status = status;
		this.userFeedbacks = userFeedbacks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "UserID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PermissionID", nullable = false)
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	@Column(name = "Email", unique = true, nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Pwd", nullable = false)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "FullName", nullable = false)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Addr", nullable = false)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "PhoneNumber", nullable = false, length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserFeedback> getUserFeedbacks() {
		return this.userFeedbacks;
	}

	public void setUserFeedbacks(Set<UserFeedback> userFeedbacks) {
		this.userFeedbacks = userFeedbacks;
	}

}
