package pojo;

// Generated Jun 7, 2015 1:31:52 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserFeedback generated by hbm2java
 */
@Entity
@Table(name = "UserFeedback")
public class UserFeedback implements java.io.Serializable {

	private int feedbackId;
	private User user;
	private String comment;

	public UserFeedback() {
	}

	public UserFeedback(int feedbackId) {
		this.feedbackId = feedbackId;
	}

	public UserFeedback(int feedbackId, User user, String comment) {
		this.feedbackId = feedbackId;
		this.user = user;
		this.comment = comment;
	}

	@Id
	@Column(name = "FeedbackID", unique = true, nullable = false)
	public int getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(int feedbackId) {
		this.feedbackId = feedbackId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "Comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
