package pojo;

// Generated Jun 7, 2015 1:31:52 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserExamination generated by hbm2java
 */
@Entity
@Table(name = "User_Examination")
public class UserExamination implements java.io.Serializable {

	private UserExaminationId id;
	private Double mark;

	public UserExamination() {
	}

	public UserExamination(UserExaminationId id) {
		this.id = id;
	}

	public UserExamination(UserExaminationId id, Double mark) {
		this.id = id;
		this.mark = mark;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "UserID", nullable = false)),
			@AttributeOverride(name = "examId", column = @Column(name = "ExamID", nullable = false)) })
	public UserExaminationId getId() {
		return this.id;
	}

	public void setId(UserExaminationId id) {
		this.id = id;
	}

	@Column(name = "Mark", precision = 53, scale = 0)
	public Double getMark() {
		return this.mark;
	}

	public void setMark(Double mark) {
		this.mark = mark;
	}

}
